### ISSUE TITLE
No longer works with latest esp-adf code

### ISSUE THREAD

**Issue by JeffDC1979** [maxgerhardt/pio-esp-adf-example#1]
This example fails to work with latest esp-adf / esp-idf code from github

**Comment by maxgerhardt** [comment]
What's weird because the ESP-ADF libraries are constant since they were downloaded once. ESP-IDF could have been updated through PIO though. Which can be fixes by specifiying the `platform` version on the `platformio.ini`. I will look into getting the latest ESP-ADF work again with the most recent ESP-IDF version available with PIO. If that doesn't work I'll fix the version numbers.

**Comment by maxgerhardt** [comment]
I just needed to remove the example firmwares, as they all have their own `main()` which we don't want since we want the `main()` from our firmware.

Updated all libs to the most recent version in commit https://github.com/maxgerhardt/pio-esp-adf-example/commit/7240a16dd2af12cd3898a26b67f6628df2e5749c. Builds with the most recent esp-idf version (`pio platform update`).
